### ISSUE TITLE
Cache list for random

### ISSUE THREAD

**Issue by stylesuxx** [lenconda/free-proxy#1]
Hey @lenconda I like this library - thank you.

I use this for testing and was wondering what you would think about caching the list for getting random proxies?

So instead of getting the list each and every time when requesting a random proxy, the list is saved the first time a random proxy is requested and by requesting a random proxy the first item of the list is popped. Once there are no more proxies in the "cached list", a new list is requested.

This would reduce the requests that one needs to make to the proxy website.

I would implement this with a new method **randomFromCache**. Let me know if this is something you want to see, then I will contribute a PR.

**Comment by lenconda** [comment]
Thank you very much for paying attention to  my project. This project was originally designed to get a random free HTTP proxy for Nodejs crawlers in order to avoid being blocked by target websites but not designed to cache free proxies. However, it is also very well if you could make a pull request for the new caching method :-).
